
import type { Project, UserProfile } from './types';

export const sampleUsers: UserProfile[] = [
    { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100', email: 'elena@example.com', bio: 'Digital artist & illustrator exploring the synergy between nature and technology.', location: 'Barcelona, Spain', status: 'Freelance Illustrator', headerUrl: 'https://picsum.photos/seed/header-elena/1200/300', socialLinks: { twitter: '#', instagram: '#' }, followers: ['sample-user-2', 'sample-user-3'], following: ['sample-user-2', 'sample-user-3', 'sample-user-4'] },
    { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100', email: 'ben@example.com', bio: 'Photographer capturing fleeting moments in urban landscapes.', location: 'New York, USA', status: 'Photographer @ Unsplash', headerUrl: 'https://picsum.photos/seed/header-ben/1200/300', socialLinks: { instagram: '#' }, followers: [], following: [] },
    { uid: 'sample-user-3', name: 'Aiko Tanaka', username: 'aikotanaka', avatarUrl: 'https://picsum.photos/seed/avatar3/100/100', email: 'aiko@example.com', bio: 'UX/UI designer crafting intuitive and beautiful digital experiences.', location: 'Tokyo, Japan', status: 'Lead UX Designer @ Nexus', headerUrl: 'https://picsum.photos/seed/header-aiko/1200/300', socialLinks: { github: '#' }, followers: [], following: [] },
    { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100', email: 'david@example.com', bio: 'Branding specialist with a passion for minimalist design.', location: 'London, UK', status: 'Creative Director', headerUrl: 'https://picsum.photos/seed/header-david/1200/300', followers: [], following: [] },
    { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100', email: 'maria@example.com', bio: '3D artist creating otherworldly scenes and characters.', location: 'Rome, Italy', status: '3D Modeler', headerUrl: 'https://picsum.photos/seed/header-maria/1200/300', followers: [], following: [] },
];

const toTimestamp = (date: string) => ({
    toDate: () => new Date(date),
}) as any;

export const sampleProjects: Project[] = [
    { id: 'sample-1', title: 'Cosmic Warrior', description: 'A powerful illustration of a cosmic warrior channeling pure energy.', category: 'Digital Art', tags: ['Anime', 'Illustration', 'Space'], keywords: ['warrior', 'power'], likes: ['sample-user-2', 'sample-user-3'], thumbnailUrl: 'https://picsum.photos/seed/anime1/600/400', mediaUrls: ['https://picsum.photos/seed/anime1/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-20T10:00:00Z') },
    { id: 'sample-2', title: 'Mountain Fighter', description: 'A character concept for a fighter living in the high mountains.', category: 'Illustration', tags: ['Character Design', 'Nature', 'Action'], keywords: ['mountain', 'combat'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime2/600/400', mediaUrls: ['https://picsum.photos/seed/anime2/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-19T14:30:00Z') },
    { id: 'sample-3', title: 'Tech Samurai', description: 'Exploring the fusion of traditional samurai aesthetics with futuristic technology.', category: 'Digital Art', tags: ['Cyberpunk', 'Samurai', 'SciFi'], keywords: ['future', 'blade'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime3/600/400', mediaUrls: ['https://picsum.photos/seed/anime3/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-18T09:00:00Z') },
    { id: 'sample-4', title: 'The Wanderer', description: 'A character concept for a fantasy game, inspired by classic shonen protagonists.', category: 'Illustration', tags: ['Character Design', 'Fantasy'], keywords: ['journey', 'hero'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime4/600/400', mediaUrls: ['https://picsum.photos/seed/anime4/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-17T18:45:00Z') },
    { id: 'sample-5', title: 'Spirit Guardian', description: 'A guardian entity protecting an ancient forest, depicted in a stylized anime format.', category: 'Digital Art', tags: ['Spirit', 'Guardian', 'Mystical'], keywords: ['forest', 'magic'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime5/600/400', mediaUrls: ['https://picsum.photos/seed/anime5/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-16T11:20:00Z') },
    { id: 'sample-6', title: 'Urban Legend', description: 'Street-style illustration of a modern-day hero in a neon-lit city.', category: 'Illustration', tags: ['Urban', 'Action', 'Neon'], keywords: ['city', 'style'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime6/600/400', mediaUrls: ['https://picsum.photos/seed/anime6/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-15T22:10:00Z') },
    { id: 'sample-7', title: 'Cloud Rider', description: 'Inspired by the classic imagery of riding on clouds, this piece explores freedom and adventure.', category: 'Illustration', tags: ['Adventure', 'Sky', 'Classic'], keywords: ['clouds', 'freedom'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime7/600/400', mediaUrls: ['https://picsum.photos/seed/anime7/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-14T13:00:00Z') },
    { id: 'sample-8', title: 'Energy Surge', description: 'Capturing the moment of intense power release during a transformation.', category: 'Digital Art', tags: ['Power', 'Effects', 'Dynamic'], keywords: ['energy', 'blast'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime8/600/400', mediaUrls: ['https://picsum.photos/seed/anime8/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-13T16:00:00Z') },
    { id: 'sample-9', title: 'Dragon Soul', description: 'A spiritual manifestation of a dragon within a martial artist.', category: 'Illustration', tags: ['Dragon', 'Soul', 'Martial Arts'], keywords: ['spirit', 'fight'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime9/600/400', mediaUrls: ['https://picsum.photos/seed/anime9/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-12T08:30:00Z') },
    { id: 'sample-10', title: 'Night Scout', description: 'A character designed for reconnaissance missions under the cover of darkness.', category: 'Illustration', tags: ['Stealth', 'Character', 'Night'], keywords: ['scout', 'dark'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime10/600/400', mediaUrls: ['https://picsum.photos/seed/anime10/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-11T19:00:00Z') },
    { id: 'sample-11', title: 'Blazing Fist', description: 'Action shot of a character delivering a fire-infused punch.', category: 'Digital Art', tags: ['Fire', 'Action', 'Combat'], keywords: ['flame', 'punch'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime11/600/400', mediaUrls: ['https://picsum.photos/seed/anime11/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-10T12:00:00Z') },
    { id: 'sample-12', title: 'Skyline Duel', description: 'Two rivals clashing high above the city skyline.', category: 'Illustration', tags: ['Duel', 'Skyline', 'Epic'], keywords: ['clash', 'heights'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime12/600/400', mediaUrls: ['https://picsum.photos/seed/anime12/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-09T14:00:00Z') },
    { id: 'sample-13', title: 'Ancestral Call', description: 'A hero hearing the voices of their ancestors during a time of need.', category: 'Digital Art', tags: ['Heritage', 'Emotional', 'Scene'], keywords: ['voices', 'past'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime13/600/400', mediaUrls: ['https://picsum.photos/seed/anime13/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-08T10:00:00Z') },
    { id: 'sample-14', title: 'Mecha Core', description: 'Intricate design of the core of a giant robotic warrior.', category: 'Digital Art', tags: ['Mecha', 'Mechanical', 'Details'], keywords: ['robot', 'core'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime14/600/400', mediaUrls: ['https://picsum.photos/seed/anime14/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-07T17:00:00Z') },
    { id: 'sample-15', title: 'Sunlight Zen', description: 'A peaceful moment of meditation at sunrise.', category: 'Illustration', tags: ['Zen', 'Peaceful', 'Sunrise'], keywords: ['calm', 'meditation'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime15/600/400', mediaUrls: ['https://picsum.photos/seed/anime15/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-06T15:00:00Z') },
    { id: 'sample-16', title: 'Thunder Strike', description: 'Dynamic illustration of a lightning-based attack.', category: 'Digital Art', tags: ['Lightning', 'Electric', 'Strike'], keywords: ['thunder', 'bolt'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime16/600/400', mediaUrls: ['https://picsum.photos/seed/anime16/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-05T11:00:00Z') },
    { id: 'sample-17', title: 'Masked Rogue', description: 'Character design for a mysterious rogue who hides their face.', category: 'Illustration', tags: ['Rogue', 'Mask', 'Mystery'], keywords: ['thief', 'shadows'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime17/600/400', mediaUrls: ['https://picsum.photos/seed/anime17/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-04T10:30:00Z') },
    { id: 'sample-18', title: 'Phoenix Rising', description: 'Symbolic piece depicting a hero rising from the ashes of defeat.', category: 'Digital Art', tags: ['Phoenix', 'Resilience', 'Symbolism'], keywords: ['rebirth', 'flame'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime18/600/400', mediaUrls: ['https://picsum.photos/seed/anime18/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-03T20:00:00Z') },
    { id: 'sample-19', title: 'Final Stand', description: 'A dramatic group shot of heroes facing an overwhelming force.', category: 'Illustration', tags: ['Heroes', 'Dramatic', 'Group'], keywords: ['team', 'last'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime19/600/400', mediaUrls: ['https://picsum.photos/seed/anime19/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, createdAt: toTimestamp('2024-05-02T14:15:00Z') },
    { id: 'sample-20', title: 'Infinite Echoes', description: 'Abstract character study exploring multiple versions of the same self.', category: 'Digital Art', tags: ['Abstract', 'Identity', 'Experimental'], keywords: ['multi', 'echo'], likes: [], thumbnailUrl: 'https://picsum.photos/seed/anime20/600/400', mediaUrls: ['https://picsum.photos/seed/anime20/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, createdAt: toTimestamp('2024-05-01T09:00:00Z') },
];
