
import type { Project, UserProfile } from './types';

export const sampleUsers: UserProfile[] = [
    { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100', email: 'elena@example.com', bio: 'Digital artist & illustrator exploring the synergy between nature and technology.', location: 'Barcelona, Spain' },
    { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100', email: 'ben@example.com', bio: 'Photographer capturing fleeting moments in urban landscapes.', location: 'New York, USA' },
    { uid: 'sample-user-3', name: 'Aiko Tanaka', username: 'aikotanaka', avatarUrl: 'https://picsum.photos/seed/avatar3/100/100', email: 'aiko@example.com', bio: 'UX/UI designer crafting intuitive and beautiful digital experiences.', location: 'Tokyo, Japan' },
    { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100', email: 'david@example.com', bio: 'Branding specialist with a passion for minimalist design.', location: 'London, UK' },
    { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100', email: 'maria@example.com', bio: '3D artist creating otherworldly scenes and characters.', location: 'Rome, Italy' },
];

const toTimestamp = (date: string) => ({
    toDate: () => new Date(date),
}) as any;

export const sampleProjects: Project[] = [
    { id: 'sample-1', title: 'Cosmic Drift', description: 'A series of abstract 3D renders exploring nebulae and cosmic phenomena.', category: 'Digital Art', tags: ['3D', 'Abstract', 'Space'], keywords: ['cosmos', 'blender'], likes: 1250, thumbnailUrl: 'https://picsum.photos/seed/proj1/600/400', mediaUrls: ['https://picsum.photos/seed/proj1/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, comments: [], createdAt: toTimestamp('2024-05-20T10:00:00Z') },
    { id: 'sample-2', title: 'Alpine Echoes', description: 'A photographic journey through the Swiss Alps.', category: 'Photography', tags: ['Landscape', 'Nature', 'Mountains'], keywords: ['alps', 'travel'], likes: 2400, thumbnailUrl: 'https://picsum.photos/seed/proj2/600/400', mediaUrls: ['https://picsum.photos/seed/proj2/1200/800'], creator: { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100' }, comments: [], createdAt: toTimestamp('2024-05-19T14:30:00Z') },
    { id: 'sample-3', title: 'Oasis Wellness App', description: 'Complete UI/UX design for a mobile wellness application.', category: 'UI/UX', tags: ['UI', 'UX', 'Mobile App'], keywords: ['figma', 'health'], likes: 3100, thumbnailUrl: 'https://picsum.photos/seed/proj3/600/400', mediaUrls: ['https://picsum.photos/seed/proj3/1200/800'], creator: { uid: 'sample-user-3', name: 'Aiko Tanaka', username: 'aikotanaka', avatarUrl: 'https://picsum.photos/seed/avatar3/100/100' }, comments: [], createdAt: toTimestamp('2024-05-18T09:00:00Z') },
    { id: 'sample-4', title: 'The Wanderer', description: 'A character concept for a fantasy game.', category: 'Illustration', tags: ['Character Design', 'Fantasy'], keywords: ['procreate', 'art'], likes: 890, thumbnailUrl: 'https://picsum.photos/seed/proj4/600/400', mediaUrls: ['https://picsum.photos/seed/proj4/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, comments: [], createdAt: toTimestamp('2024-05-17T18:45:00Z') },
    { id: 'sample-5', title: 'NORD Branding', description: 'Branding and identity project for a fictional Scandinavian furniture company.', category: 'Branding', tags: ['Branding', 'Minimalist', 'Logo'], keywords: ['scandinavian', 'design'], likes: 1500, thumbnailUrl: 'https://picsum.photos/seed/proj5/600/400', mediaUrls: ['https://picsum.photos/seed/proj5/1200/800'], creator: { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100' }, comments: [], createdAt: toTimestamp('2024-05-16T11:20:00Z') },
    { id: 'sample-6', title: 'Tokyo at Night', description: 'Street photography series capturing the vibrant and electric atmosphere of Tokyo after dark.', category: 'Photography', tags: ['Street Photography', 'Night', 'City'], keywords: ['tokyo', 'neon'], likes: 4200, thumbnailUrl: 'https://picsum.photos/seed/proj6/600/400', mediaUrls: ['https://picsum.photos/seed/proj6/1200/800'], creator: { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100' }, comments: [], createdAt: toTimestamp('2024-05-15T22:10:00Z') },
    { id: 'sample-7', title: 'Cybernetic Dreams', description: 'A vibrant digital painting exploring themes of cyberpunk and human augmentation.', category: 'Digital Art', tags: ['Cyberpunk', 'SciFi', 'Portrait'], keywords: ['futuristic', 'digital painting'], likes: 1800, thumbnailUrl: 'https://picsum.photos/seed/proj7/600/400', mediaUrls: ['https://picsum.photos/seed/proj7/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, comments: [], createdAt: toTimestamp('2024-05-14T13:00:00Z') },
    { id: 'sample-8', title: 'Artisan Coffee Packaging', description: 'Packaging design for a boutique coffee brand.', category: 'Branding', tags: ['Packaging', 'Illustration', 'Coffee'], keywords: ['branding', 'design'], likes: 950, thumbnailUrl: 'https://picsum.photos/seed/proj8/600/400', mediaUrls: ['https://picsum.photos/seed/proj8/1200/800'], creator: { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100' }, comments: [], createdAt: toTimestamp('2024-05-13T16:00:00Z') },
    { id: 'sample-9', title: 'Celestial Visions', description: '3D motion graphics piece depicting a journey through a fantastical solar system.', category: 'Digital Art', tags: ['3D', 'Motion Graphics', 'Animation'], keywords: ['after effects', 'cinema 4d'], likes: 2900, thumbnailUrl: 'https://picsum.photos/seed/proj9/600/400', mediaUrls: ['https://picsum.photos/seed/proj9/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, comments: [], createdAt: toTimestamp('2024-05-12T08:30:00Z') },
    { id: 'sample-10', title: 'Forest Spirits', description: 'A series of enchanting illustrations of mystical creatures in a moonlit forest.', category: 'Illustration', tags: ['Illustration', 'Fantasy', 'Creatures'], keywords: ['forest', 'magic'], likes: 1640, thumbnailUrl: 'https://picsum.photos/seed/proj10/600/400', mediaUrls: ['https://picsum.photos/seed/proj10/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, comments: [], createdAt: toTimestamp('2024-05-11T19:00:00Z') },
    { id: 'sample-11', title: 'Monochrome Portraits', description: 'A powerful series of black and white portraits.', category: 'Photography', tags: ['Portrait', 'b&w', 'Studio'], keywords: ['people', 'monochrome'], likes: 3500, thumbnailUrl: 'https://picsum.photos/seed/proj11/600/400', mediaUrls: ['https://picsum.photos/seed/proj11/1200/800'], creator: { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100' }, comments: [], createdAt: toTimestamp('2024-05-10T12:00:00Z') },
    { id: 'sample-12', title: 'Fintech Dashboard UI', description: 'UI concept for a modern and clean financial technology dashboard.', category: 'UI/UX', tags: ['UI', 'Dashboard', 'Fintech'], keywords: ['data visualization', 'finance'], likes: 2200, thumbnailUrl: 'https://picsum.photos/seed/proj12/600/400', mediaUrls: ['https://picsum.photos/seed/proj12/1200/800'], creator: { uid: 'sample-user-3', name: 'Aiko Tanaka', username: 'aikotanaka', avatarUrl: 'https://picsum.photos/seed/avatar3/100/100' }, comments: [], createdAt: toTimestamp('2024-05-09T14:00:00Z') },
    { id: 'sample-13', title: 'Botanic Geometry', description: 'A branding project for a luxury soap company, combining floral elements with geometric patterns.', category: 'Branding', tags: ['Branding', 'Pattern', 'Luxury'], keywords: ['floral', 'geometry'], likes: 1100, thumbnailUrl: 'https://picsum.photos/seed/proj13/600/400', mediaUrls: ['https://picsum.photos/seed/proj13/1200/800'], creator: { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100' }, comments: [], createdAt: toTimestamp('2024-05-08T10:00:00Z') },
    { id: 'sample-14', title: 'The Golem', description: 'A massive, ancient golem character model, fully textured and rigged.', category: 'Digital Art', tags: ['3D', 'Character Model', 'Fantasy'], keywords: ['zbrush', 'substance painter'], likes: 1950, thumbnailUrl: 'https://picsum.photos/seed/proj14/600/400', mediaUrls: ['https://picsum.photos/seed/proj14/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, comments: [], createdAt: toTimestamp('2024-05-07T17:00:00Z') },
    { id: 'sample-15', title: 'Desert Solitude', description: 'Landscape photography from a trip through the Atacama Desert.', category: 'Photography', tags: ['Landscape', 'Desert', 'Travel'], keywords: ['atacama', 'chile'], likes: 2800, thumbnailUrl: 'https://picsum.photos/seed/proj15/600/400', mediaUrls: ['https://picsum.photos/seed/proj15/1200/800'], creator: { uid: 'sample-user-2', name: 'Ben Carter', username: 'bencarter', avatarUrl: 'https://picsum.photos/seed/avatar2/100/100' }, comments: [], createdAt: toTimestamp('2024-05-06T15:00:00Z') },
    { id: 'sample-16', title: 'Children\'s Book Illustrations', description: 'A collection of whimsical illustrations for a children\'s story book.', category: 'Illustration', tags: ['Illustration', 'Kids', 'Storybook'], keywords: ['children', 'whimsical'], likes: 2150, thumbnailUrl: 'https://picsum.photos/seed/proj16/600/400', mediaUrls: ['https://picsum.photos/seed/proj16/1200/800'], creator: { uid: 'sample-user-1', name: 'Elena Garcia', username: 'elenag', avatarUrl: 'https://picsum.photos/seed/avatar1/100/100' }, comments: [], createdAt: toTimestamp('2024-05-05T11:00:00Z') },
    { id: 'sample-17', title: 'Music Player App UI', description: 'A dark-mode UI for a conceptual music streaming application.', category: 'UI/UX', tags: ['UI', 'Mobile App', 'Dark Mode'], keywords: ['music', 'spotify'], likes: 1890, thumbnailUrl: 'https://picsum.photos/seed/proj17/600/400', mediaUrls: ['https://picsum.photos/seed/proj17/1200/800'], creator: { uid: 'sample-user-3', name: 'Aiko Tanaka', username: 'aikotanaka', avatarUrl: 'https://picsum.photos/seed/avatar3/100/100' }, comments: [], createdAt: toTimestamp('2024-05-04T10:30:00Z') },
    { id: 'sample-18', title: 'Liquid Chrome', description: 'An experimental 3D project playing with liquid metal simulations.', category: 'Digital Art', tags: ['3D', 'Abstract', 'Experimental'], keywords: ['houdini', 'chrome'], likes: 3200, thumbnailUrl: 'https://picsum.photos/seed/proj18/600/400', mediaUrls: ['https://picsum.photos/seed/proj18/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, comments: [], createdAt: toTimestamp('2024-05-03T20:00:00Z') },
    { id: 'sample-19', title: 'Vintage Tea Co. Branding', description: 'A complete branding suite for a vintage-style tea company.', category: 'Branding', tags: ['Branding', 'Vintage', 'Packaging'], keywords: ['tea', 'retro'], likes: 1300, thumbnailUrl: 'https://picsum.photos/seed/proj19/600/400', mediaUrls: ['https://picsum.photos/seed/proj19/1200/800'], creator: { uid: 'sample-user-4', name: 'David Chen', username: 'davidchen', avatarUrl: 'https://picsum.photos/seed/avatar4/100/100' }, comments: [], createdAt: toTimestamp('2024-05-02T14:15:00Z') },
    { id: 'sample-20', title: 'Architectural Renders', description: 'A collection of photorealistic architectural visualizations for a modern villa.', category: 'Digital Art', tags: ['Architecture', '3D', 'Realism'], keywords: ['vray', '3dsmax', 'archviz'], likes: 2550, thumbnailUrl: 'https://picsum.photos/seed/proj20/600/400', mediaUrls: ['https://picsum.photos/seed/proj20/1200/800'], creator: { uid: 'sample-user-5', name: 'Maria Rossi', username: 'mariarossi', avatarUrl: 'https://picsum.photos/seed/avatar5/100/100' }, comments: [], createdAt: toTimestamp('2024-05-01T09:00:00Z') },
];
